spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springapi?autoReconnect=true&useSSL=false
    username: springapi
    password: springapi
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update

logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  org.hibernate:
    SQL: DEBUG
    type:
      descriptor.sql.BasicBinder: trace
      EnumType: trace